### ISSUE TITLE
Making Retrieval Possible in Fastboot (Enhancement)

### ISSUE THREAD

**Issue by alexmasita** [mikkopaderes/ember-cloud-firestore-adapter#102]
@mikkopaderes. This Addon is great so far and I would not want to raise this as an issue but an enhancement.  It would be great if the Find Record firebase calls could work in fastboot as well so we:

1. Do not have to put fastboot checks on the calls.
2. Benefit from server side retrieval therefore have more info on the relevant pages on first render.
3. As well as gain the SEO benefits of server side rendering for firebase data. 

I would assume the adapter would need to be re-architected in such a way as to be able to use node firebase libraries to retrieve the data.

As stated, this is not an issue, so feel free to close it if you think it is not something that could be on your road map soon.  I would be willing to look into this as well with a view to submit a pull request.  Thank you.

**Comment by mikkopaderes** [comment]
It's supposed to work. Is it not for you?

**Comment by alexmasita** [comment]
Interesting. I had assumed that this was an issue because previously my app had, a while back, blown up in fastboot and I had to put in fastboot checks all over the app which resolved the issue but it is possible something else was the issue and I might have fixed it without knowing in due course.  Will close this for now until I actually hit the issue again conclusively.  Thanks :).
