### ISSUE TITLE
Accessing deeply nested collections

### ISSUE THREAD

**Issue by conormag** [mikkopaderes/ember-cloud-firestore-adapter#106]
Hi @mikkopaderes, thanks for a great adapter!

I have collections clients -> athletes and clients -> teams. everything works great. I can access athletes and teams with calls like` client.get('athletes)` and `client.get('teams')`.

when i add a many-to-many relationship between athletes and teams everything mostly works as expected but i can no longer use accessors to retrieve child items. eg. if in a model hook i have loaded a team then any attempt to load a team's athletes via `team.get('athletes')` will return an empty recordset and i can only retrieve a team' s athletes via a `store.query`.

If I inspect the buildReference for a team's athletes, the path appears as `team\:team_id\athletes`. I'm guessing this would need to be `clients\:client_id\teams\:team_id\athletes` but I don't know how this would be doable in a model definition?

**Comment by mikkopaderes** [comment]
May I see how you've defined your models?

**Comment by conormag** [comment]
there are no belongsTo anywhere

```
// team model
export default Model.extend(Validations, {
  name: attr('string'),
  athletes: hasMany('athlete', {
    isRealtime: true
  }),
 ...

// client model
export default Model.extend(Validations, {

  users: hasMany('clientUser'),

  athletes: hasMany('athlete', {
    isRealtime: true,
  }),

  teams: hasMany('team', {
    isRealtime: true,
  }),
  ....

// athlete model

export default Model.extend(Validations, {

  teams: hasMany('team'),

```

**Comment by mikkopaderes** [comment]
> If I inspect the buildReference for a team's athletes, the path appears as team\:team_id\athletes. I'm guessing this would need to be clients\:client_id\teams\:team_id\athletes but I don't know how this would be doable in a model definition?

Yes it should be `teams/:teamid/atheletes` by default. Does your that subcollection have any documents?

**Comment by conormag** [comment]
> Does that subcollection have any documents?

Yes, a collection of documents that each contain a single referenceTo field to 

`clients/:client_id/athletes/:athlete_id` and where the document id is the same as  that `:athlete_id`

**Comment by mikkopaderes** [comment]
Ok, got it. Just to confirm, here's the data structure that you have:

```json
{
  "clients": {
    "client_1": {
      "athletes": {
        "athelete_1": { ... }
      }
    }
  },

  "teams": {
    "team_1": {
      "athletes": {
        "athlete_1": {
          "referenceTo": "/clients/client_1/athletes/athlete_1"
        }
      }
    }
  }
}
```

This should work fine as it is. I'll try to find some time to reproduce it. As a follow up question:

1. I'm curious what are the contents of `/clients/client_1/athletes/athlete_1`?
2. How do you do the `store.query` to make it work?

Also, if `store.query` works for you, maybe a better temporary workaround is to override the [`buildReference`](https://mikkopaderes.github.io/ember-cloud-firestore-adapter/docs/relationships.html#buildreference) of `teams.get('athletes')` in the model definition.

**Comment by conormag** [comment]
The structure is a little different from that. A client has 1 or more  athletes and 0 or more teams. Athletes can be in 0 or more teams.
 Its:

```
{
  "clients": {
    "client_1": {
        "athletes": {
            "athlete_1": { 
                 .... other doc attributes ....
                 "teams": { 
                    "team_1": { 
                       "referenceTo": "/clients/client_1/teams/team_1"
                     }
                 }
             }
         },
        "teams": {
           "team_1": {
              "athletes": {
                   "athlete_1": {
                      "referenceTo": "/clients/client_1/athletes/athlete_1"
                   }
               }
           }
        }
    }
  }
}
```

for the query, i have to know the client id and team id to get a teams athletes

```
    this.store.query('athlete', {
      buildReference(db) {
        return db.collection('clients')
        .doc(_this.get('client.id'))
        .collection('teams').doc(_this.get('team.id')).collection('athletes');
      }
    })
```

I just want to make the point also that I'm looking to store all of a client's info in a tree structure within a client, ie no root level collections with cross-client info.

**Comment by conormag** [comment]
did you get a chance to look at this @mikkopaderes ?

**Comment by mikkopaderes** [comment]
No, unfortunately. Currently in a long vacation and wouldn't be back till mid-December.

**Comment by mikkopaderes** [comment]
Ok, reading back through this I think what you should need to do is to use [`buildReference()`](https://mikkopaderes.github.io/ember-cloud-firestore-adapter/docs/relationships.html#buildreference) in the model definition since your documents lives under specific sub-collections. Does this work for you?

**Comment by conormag** [comment]
It sort of does. I need to revisit it. It would involve injecting a service into the model which would have the doc ids needed to build the reference tree - which is probably an anti-pattern in Ember. Doing something with collection groups could also be a possibility. 

I'm happy to close the issue and come back again with something more concrete?

**Comment by mikkopaderes** [comment]
I may be wrong but looking at your structure, it seems that you only need client id and team id to get a team's atheletes. You already have access to team id so you'll just have to find a way to make client id available to the team record if it isn't yet.

**Comment by conormag** [comment]
that's true but I gave the minimum viable example to explain my issue. there are further levels of nesting under athletes with resources that have varying relationship types

**Comment by mikkopaderes** [comment]
I think it's a little bit challenging because of how you structured your data with very deep nesting. There's not much I could do for this as the code is working as intended. Maybe you are better of using `query` for the very complex nesting.

**Comment by conormag** [comment]
agreed Mikko. closing the issue.
