### ISSUE TITLE
Write fails if batchSize limit is exceeded

### ISSUE THREAD

**Issue by DavidPhilip** [mikkopaderes/ember-cloud-firestore-adapter#107]
Just wanted to point out that currently a batch defined via the include option which holds more changes than 500 write operations (which is the limit defined by Google Firestore) will cause the whole write operation to fail.

One option would be to split all batched mutations up into multiple batches of 500 and finally invoke their commit.

**Comment by mikkopaderes** [comment]
I'm inclined to not support this as doing bulk operations isn't recommended by the Firebase team. You'd be better off by doing those operations on the server and using parallelized individual writes if possible.

[Reference](https://stackoverflow.com/a/58897275)
