### ISSUE TITLE
Query fails if doc referenced by referenceTo field does not exist

### ISSUE THREAD

**Issue by conormag** [mikkopaderes/ember-cloud-firestore-adapter#108]
Lets say I have post model and posts collection and elsewhere in my db I have a sub-collection of posts that are docs with a referenceTo field to the actual posts collection. 

If I perform a query on the sub-collection and one of the reference fields references a post that doesn't exist the query rejects ([findRecord](https://github.com/mikkopaderes/ember-cloud-firestore-adapter/blob/master/addon/adapters/cloud-firestore.js) rejects on falsy `snapshop.exists` property) eg.

```
this.store.query('post', { 
   buildReference(db) { 
      return db.collection('some').doc('docWithPostSubCollectionOfReferenceTos').collection('posts'); 
   }
}
```
rejects if one of the references is broken.

But given that Firestore operates in the mode that a given DocumentReference will return a DocumentSnapshot with an exists property = false if there is no snapshot at the reference, would it be more more appropriate for the adapter to return a record that satisfies the DS.Model [isEmpty ](https://api.emberjs.com/ember-data/3.14/classes/Model/properties/isEmpty?anchor=isEmpty)state?

(In my particular scenario, I have instances where the referenceTo field can legitimately exist without the referenced record - long running cascading delete functions that run on an onDelete trigger. If the user goes elsewhere in the app I would prefer the queries to succeed and handle the isEmpty records in template logic.)

Maybe an `adapterOptions` to determine how missing references are handled?

**Comment by mikkopaderes** [comment]
I still feel uneasy about this, `DS.Model.isEmpty` is the first state for when a record is created whereas yours it's something that's about to be deleted.

I think what you should do instead is to first remove the sub-collection documents before removing the actual documents being pointed to by those `referenceTo` fields.

**Comment by conormag** [comment]
Thanks Mikko.

Its the deletion of the actual document that triggers the function to delete the references. My only other viable option is to rewrite it as a https callable and enforce a loading spinner on the user. Either way the cloud function is pretty much cold starting every time which means a 5-10sec delay for completion.

The isEmpty doc does say "A record can also enter the empty state if the adapter is unable to locate the record."

I'd be happy to submit a PR if you would consider it. An adapterOptions addition with "allowEmptyReferences" boolean?

**Comment by conormag** [comment]
Another option is that query just returns documents that had a valid reference?

**Comment by mikkopaderes** [comment]
@conormag I'd go for the latter where we don't include problematic records as part of the return. I'm trying to limit the APIs inside the `adapterOptions` so as we don't keep on adding unto it per every use-case. The solution seems like a sane default so I'm all in for it.

Are you still willing to make a PR?

**Comment by conormag** [comment]
yes, I'll submit a PR in the next week or so.
