### ISSUE TITLE
Namespaced/nested models

### ISSUE THREAD

**Issue by charlesfries** [mikkopaderes/ember-cloud-firestore-adapter#117]
I have models that are in a subdirectory of my models folder `e.g. models/other/contract`. I think they are called "namespaced models" in the docs. I am **not** referring to subcollections.

When I save these namespaced models, I get the following error:

`Invalid collection reference. Collection references must have an odd number of segments, but other/contracts has 2`

So it seems the adapter is trying to write to a collection with a slash in the collection identifier. I can get around the error by rewriting the Firestore collection name as `other.contracts`, but is there a recommended way of doing this?

**Comment by mikkopaderes** [comment]
I'm not aware of namespaced models. Can you link me the docs to it?

**Comment by mikkopaderes** [comment]
Inactive issue
