### ISSUE TITLE
can`t createRecord without id

### ISSUE THREAD

**Issue by it-delta** [mikkopaderes/ember-cloud-firestore-adapter#145]
const newPost = this.store.createRecord('post', { title: 'Post A' });

the error is "Cannot read property 'toString' of undefined TypeError: Cannot read property 'toString' of undefined"
in the function

    generateIdForRecord(_store, type) {
      const db = this.firebase.firestore();
      const collectionName = (0, _buildCollectionName.default)(type.modelName);
      return db.collection(collectionName).doc().id;
    }

var type is just string (Model name) so type.modeName is undefined

**Comment by mikkopaderes** [comment]
This is weird, `type` isn't supposed to be a string, even the ember-data docs says so. What version of the adapter and ember-data are you using?

**Comment by it-delta** [comment]
Yes, it`s weird
https://i.imgur.com/iJV46wr.png

I used Emberfire and everything  worked fine
The ember-data version is 3.23.0

I had to change "type.modelName" to "type" and now it works )))

How can I help you to find a problem... ?

P.S. Thanks for great addon! )

**Comment by mikkopaderes** [comment]
Ok, I've dug into this and found out that the type IS a string and that previous versions of this library was correctly identifying it as so.

When I migrated the code to TypeScript, I've been getting different type suggestions and even the API docs says that it also is another type which may resulted in this regression bug. Sadly, I didn't have acceptance tests for creating records _without any IDs_. I'll fix this ASAP and add those tests so avoid future regression bugs.

Thanks for reporting!

**Comment by it-delta** [comment]
Thank you so much!
