### ISSUE TITLE
Namespace at the adapter/serializer level?

### ISSUE THREAD

**Issue by dknutsen** [mikkopaderes/ember-cloud-firestore-adapter#150]
First of all, thank you very much for this addon. It's exactly what I was looking for after revisiting Emberfire and finding it in WIP and basically abandoned state. I love the lightweight, flexible, no-nonsense approach you took.

I'm looking for a way to "namespace" the default read/write operations at the adapter/serializer level. My use case would be similar to the [emberfire `namespace` attribute](https://github.com/mikkopaderes/ember-cloud-firestore-adapter/issues/new) on the firestore adapter. For example if I had a model "item" and wanted the "items" collection to be written to/read from at `environments/<build env>/users/<uid>/items` instead of just root `items` it would be very nice to just have to specify a namespace in one place like the adapter e.g. something like
```
  get namespace() {
    return `/environments/${config.environment}/users/${this.currentUser.userId}`;
  }
```

Is this possible currently? And if not would you be open to supporting something like this? I'd be happy to contribute a PR if so.

**Comment by mikkopaderes** [comment]
This is currently supported via `buildReference` hooks when creating or finding records. You can check it out in the docs [here](https://github.com/mikkopaderes/ember-cloud-firestore-adapter/blob/master/docs/finding-records.md#buildreference) and [here](https://github.com/mikkopaderes/ember-cloud-firestore-adapter/blob/master/docs/create-update-delete-records.md#buildreference).

**Comment by dknutsen** [comment]
Yeah the reason I'm looking for it at the adapter level specifically is to avoid duplicating a lot of the same buildReference methods all over the place (it would really only vary on a per-adapter basis). It seems like a common enough use case. But it seems I can just add some code to my application adapter that more or less does the trick, something along these lines:

```
  buildReference = (db) => db.collection('environments').doc('staging').collection('users').doc('basic-user').collection('items');

  findRecord(store, type, id, snapshot) {
    if (!snapshot.adapterOptions) snapshot.adapterOptions = { };
    if (!snapshot.adapterOptions.buildReference) {
      snapshot.adapterOptions.buildReference = this.buildReference;
    }
    return super.findRecord(store, type, id, snapshot);
  }
```

I'll keep playing around with it. Thanks for the swift response!

**Comment by mikkopaderes** [comment]
Hmm, another way to do it is maybe have a configuration utility where you can just source the path from there.

That way, you can just change the config values and all your codes that references that will get updated immediately.

This might be a more clean way to do rather than editing the adapter. But yeah, whatever works for your case. 😉

**Comment by dknutsen** [comment]
@mikkopaderes one last question, how would this work with one-to-many relationships? It states in the docs that buildReference is ignored in that case, and I'm not seeing an easy way to set the base ref for the relationship query based on the code (but I haven't stepped through it yet).

**Comment by mikkopaderes** [comment]
If any, one-to-many relationship is the easiest to work around with in this library.

What do you have right now and what's the problem that you're encountering?

**Comment by dknutsen** [comment]
Well I was just playing around with it using very basic models:
```
// app/models/box.js
export default Model.extend({
  label: attr('string'),
  things: hasMany('thing', {
    inverse: 'box',
  })
});

// app/models/thing.js
export default Model.extend({
  label: attr('string'),
  box: belongsTo('box', {
    inverse: 'things',
  })
});
```

So first I created one of each at the root of the db and linked them (just using browser console):
```
var box1 = $E.createRecord('box', { label: 'box1' }).save();
var thing1 = $E.createRecord('thing', { label: 'thing1', box: box1 }).save();
```
This works great since everything is at the root.

Next I wanted to try "namespacing" them at `/environments/staging` so I made modifications to the models (even though neither is implemented by the adapter) to demonstrate what I'm going for:
```
export default Model.extend({
  label: attr('string'),
  things: hasMany('thing', {
    inverse: 'box',
    // buildReference is ignored for one-to-many according to docs
    buildReference: (db) => db.collection('environments').doc('staging').collection('things')
  })
});

export default Model.extend({
  label: attr('string'),
  box: belongsTo('box', {
    inverse: 'things',
    // this isn't implemented for belongsTo accoriding to docs
    buildReference: (db) => db.collection('environments').doc('staging').collection('boxes')
  })
});
```
Then tried to make new models using my "namespace":
```
var box2 = $E.createRecord('box', { label: 'box2' });
box2.save({ adapterOptions: { buildReference: (db) => db.collection('environments').doc('staging').collection('boxes') } });
var thing2 = $E.createRecord('thing', { label: 'thing2', box: box2 });
thing2.save({ adapterOptions: { buildReference: (db) => db.collection('environments').doc('staging').collection('things') } });
```
The saves work fine, and the records are created in the right places, but `thing2` is serialized with a box reference of `boxes/b8VwwMqYsdIAof0YKj2z` (root level collection, not "namespaced"). 

Further, if I try to fetch the hasMany for box2 it makes a query on the root `boxes` collection rather than the "namespaced" one, presumably because the one-to-many relationship ignores the buildReference method. 

So specifically for a one-to-many hasMany relationship it seems to always expect the collections to be at the root. Or maybe I'm missing something... Is there a way to "namespace" this type of relationship too? Everything else seems to work as expected.

**Comment by mikkopaderes** [comment]
Thanks, I understand now. Yes, this is a bug as it's a use-case that I don't get to normally see. Will put these in my TODO for the week:

- Support `buildReference` on `hasMany` side for one-to-many relationship
- Fix serialization of `belongsTo` when saving record on a namespaced path

**Comment by dknutsen** [comment]
That would be amazing, thanks for all the help!

**Comment by mikkopaderes** [comment]
Spent a little time looking into this. There doesn't seem to be a way to check where a `belongsTo` relationship will be referenced to right now by the time that we're saving a record. So rather than a bug, it's more of a *not supported* issue.

In order to support this, I'll have to add `buildReference` API for the `belongsTo` options so that every time a `belongsTo` gets saved, it will check first if a `buildReference` exists and save to whatever collection that gets resolved to.

e.g.

```javascript
export default Model.extend({
  box: belongsTo('box', {
    buildReference: (db) => db.collection('environments').doc('staging').collection('boxes')
  })
});
```

Will create an issue by today to track the progress of this feature request
