### ISSUE TITLE
Multiple filters support

### ISSUE THREAD

**Issue by tpetrone** [mikkopaderes/ember-cloud-firestore-adapter#153]
User Story:

As a user, I want to be able to **conditionally** apply multiple filters when querying Firebase.

Given `3` query parameters that are mutated by the User from the UI;
In model hook, I want to build the query based on `params` that the user interacted to.

Code example

```js
model(params) {
  return this.store.query('modelName', {
    filter(reference) {
      return reference
        .orderBy('property-1')
        .where('property-1', '>', params['queryParam-1'])   // executed **only** when the user changes queryParam-1 query
        .where('property-1', '<', params['queryParam-2'])   // executed **only** when the user changes queryParam-2 query
        .where('property-2', '==', params['queryParam-3'])  // executed **only** when the user changes queryParam-3 query
    }
  })
}
```

**Comment by mikkopaderes** [comment]
I don't think this is ideal. You should probably make use of [`Route.refresh()`](https://api.emberjs.com/ember/3.24/classes/Route/methods/refresh?anchor=refresh) instead.

**Comment by tpetrone** [comment]
I am refreshing the route via

```js
  queryParams = {
    queryParam-1: {
      refreshModel: true,
    },
    queryParam-2: {
      refreshModel: true,
    },
    queryParam-3: {
      refreshModel: true,
    }
  };
```
since I need model hook to fire everytime the user changes the `queryParams`.
Can you elaborate?

**Comment by mikkopaderes** [comment]
What you're doing actually seems a good and ember-ish way so you should probably continue with that

**Comment by mikkopaderes** [comment]
But I may not have understood your problem. What do you mean by conditionally apply multiple filters?

**Comment by mikkopaderes** [comment]
The problem you have isn't within the scope of the adapter. Since `filter` is a function, you're in full control already on what query you want to execute. You can place the condition there.

**Comment by tpetrone** [comment]
Right, my problem is that I need to chain those methods.
When you say "place the condition there" what do you mean?

As far as I can say, my options are:
- Cover all possibilities of the filters occurrence:
  - `switch case` for every filter alone and every possible combination. 7 in total. (Feels very verbose)
- [Optional chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) (Feels hacky, since the object itself wouldn't have the properties)
- Call a default query in the place the ones user didn't interacted to. If the user does not set any `queryParam` I would repeat the same query three times. (Feels very hacky)
- Call an opposite query in the place the ones user didn't interacted to , ('property-1', '!=', null) for instance. (Seems logic but I would bump in Firebase limitations)
---
Any other thoughts?  
Thanks in advance

As a benchmark, what Emberfire does is to receive an _array of arrays_ for `where` argument and then `spread` it to mount the query that actually goes to Firebase.

**Comment by mikkopaderes** [comment]
Sorry, I'm still super confused with what you're trying to achieve. You said that:

> As a user, I want to be able to **conditionally** apply multiple filters when querying Firebase.

If you want to conditionally apply filters then just wrap them in an if-condition:

```javascript
if (...) {
  this.store.query('modelName', {
    filter(reference) {
      return reference.orderBy('property-1').where('property-1', '>', params['queryParam-1']);
    }
} else {
  this.store.query('modelName', {
    filter(reference) {
      return reference.orderBy('property-1').where('property-1', '<', params['queryParam-2']);
    }
}

// OR

this.store.query('modelName', {
  filter(reference) {
    if (...) {
      return reference.orderBy('property-1').where('property-1', '>', params['queryParam-1']);
    }

    return reference.orderBy('property-1').where('property-1', '<', params['queryParam-2']);
  }
}
```

But if you want to chain filters as per:

> Right, my problem is that I need to chain those methods.

Then it already works. You have to remember that `reference` in `filter(reference)` is just a [`CollectionReference`](https://firebase.google.com/docs/reference/js/firebase.firestore.CollectionReference). Whatever it supports, the adapter will support as well, and whatever the limitation it has, the adapter will have that limitation as well.

**Comment by tpetrone** [comment]
Alright, thanks for the effort.
I will try to make myself clearer:

In my example, the user has the ability to filter **simultaneously** from three different fields.
Nevertheless, not necessarily.

So, if I have `property-1`, `property-2` and `property-3` and if I follow your instructions, I would need to have exactly seven `if clauses` to cover all the possibilities. For instance:

```js
if (params.queryParam-1 && !params.queryParam-2 && !queryParam-3) {
  // Filter only by property-1
} else if (!params.queryParam-1 && params.queryParam-2 && !queryParam-3) {
  // Filter only by property-2
} else if (!params.queryParam-1 && !params.queryParam-2 && queryParam-3) {
  // Filter only by property-3
} else if (params.queryParam-1 && params.queryParam-2 && !queryParam-3) {
  // Filter only by property-1 AND property-2
} else if (params.queryParam-1 && !params.queryParam-2 && queryParam-3) {
  // Filter only by property-1 AND property-3
} else if (!params.queryParam-1 && params.queryParam-2 && queryParam-3) {
  // Filter only by property-2 AND property-3
} else if (params.queryParam-1 && params.queryParam-2 && queryParam-3) {
  // Filter only by property-1 AND property-2 AND property-3
}
```

What I wanted to do:

```js
if (params.queryParam-1) {
  // Append to filter chain property-1
} 

if (params.queryParam-2) {
  // Append to filter chain property-2
}

if (params.queryParam-3) {
  // Append to filter chain property-3
}

// Return query
```

**Comment by mikkopaderes** [comment]
```javascript
if (params.queryParam-1) {
  reference.where('property-1', '>', params['queryParam-1']);
} 

if (params.queryParam-2) {
  reference.where('property-1', '>', params['queryParam-2']);
}

if (params.queryParam-3) {
  reference.where('property-1', '>', params['queryParam-3']);
}

return reference;
```

Is this what you're looking for? That's already support if so. Again, whatever will work from Firestore's API you'll be able to do it in this Adapter as well. If it's not possible, then it's not possible here as well.

For this project, I tend to avoid adding convenience features. I would like to stick to whatever Firestore gives us for more flexibility and less maintenance.
