### ISSUE TITLE
Improve Docs

### ISSUE THREAD

**Issue by tpetrone** [mikkopaderes/ember-cloud-firestore-adapter#154]
Docs doesn't mention how you setup the serializer.
It was pretty guessable though.

After generating an application adapter with `ember generate serializer application`  
One needs to change the file content to:

```js
import CloudFirestoreSerializer from 'ember-cloud-firestore-adapter/serializers/cloud-firestore';

export default class ApplicationSerializer extends CloudFirestoreSerializer {
}
```

**Comment by mikkopaderes** [comment]
Fixed
