### ISSUE TITLE
Query belongsTo

### ISSUE THREAD

**Issue by tpetrone** [mikkopaderes/ember-cloud-firestore-adapter#155]
Given a model `Comment` that belongsTo `User` (User hasMany Comments).
Since _one-to-many_ relationships only keep the reference in the belongsTo side.

What should be the preferred way to query all comments from a specific User?

**Comment by mikkopaderes** [comment]
It will work as-is the adapter knows how to fetch it correctly. Just that be aware of how it's gonna get stored in Firestore.

**Comment by tpetrone** [comment]
@mikkopaderes Can you elaborate?

Let me emphasize that this is a **query**. 
I am not looking after doing `user.get('comments')`.

There are other filters to be applied.

```js
this.store.query('modelName', {
  filter(reference) {
    return reference
    .where('property-1', '==', 'queryParam-1')
    .where(/* code to filter by user */)
  }
})
```

**Comment by mikkopaderes** [comment]
```javascript
const firestore = this.firebase.firestore();

this.store.query('modelName', {
  filter(reference) {
    return reference
      .where('property-1', '==', 'queryParam-1')
      .where('user', '==', db.collection('users').doc('<user_id>'));
  }
})
```
