### ISSUE TITLE
Feature request: Add error name to error thrown when fetchRecord fails

### ISSUE THREAD

**Issue by conormag** [mikkopaderes/ember-cloud-firestore-adapter#159]
the adapter's findRecord etc call an underlying fetchRecord function which rejects with a js Error object when a record isn't found:

`reject(new Error(`Record ${id} for model type ${type.modelName} doesn't exist`));`

It would be nice if this error object also had a name property `not-found` making it easier to identify the specific error. 'not-found' would match the naming conventions of the FirestoreError class.

**Comment by mikkopaderes** [comment]
Thanks. I'll be looking into this more in the next few days.
