### ISSUE TITLE
Fastboot + firebase functions

### ISSUE THREAD

**Issue by mamiller93** [mikkopaderes/ember-cloud-firestore-adapter#160]
Could you flesh out the architecture of using a service worker connected to a functions app server? I must be missing a puzzle piece since my service worker doesn't try to connect to my running functions port to get the correct custom tokenID. Instead, since it doesn't use the functions app server, the tokenID it has is "incorrect", which means it's not authenticated in fastboot. I'm hoping for a little more guidance in setting this up.

**Comment by mikkopaderes** [comment]
Have you seen the guide I have for fastboot authentication? 

Perhaps you've cached your app for offline availability as a PWA in your service-worker? If so, then this means that it will avoid fastboot call and instead will serve the app directly in your clients device cache.

**Comment by mamiller93** [comment]
@mikkopaderes you're referencing [this page](https://github.com/mikkopaderes/ember-cloud-firestore-adapter/blob/fe4d05a8cff19a0b383c7188f5b392334b83f41c/docs/authentication.md), right? If so, I followed it to a T. Though, to be honest, I wasn't entirely sure where to put the server portion - so I put it in a cloud function, identically (I believe) to what you described. 

When I say flesh out the architecture, I guess I really want to double check my understanding of the role of the cloud functions server.

When a user loads the page for the first time, they won't be authenticated and fastboot will agree. When the user signs in for the first time, that request goes directly to firebase.auth() to be authenticated. If the user refreshes the page, the service worker that is registered updates the fetch request with the token. How did the service worker get the custom token from the functions server?

**Comment by mikkopaderes** [comment]
> When a user loads the page for the first time, they won't be authenticated and fastboot will agree.

Yes

> When the user signs in for the first time, that request goes directly to firebase.auth() to be authenticated.

Yes, and to be specific, the `firebase.auth()` of the client itself, not the server.

> If the user refreshes the page, the service worker that is registered updates the fetch request with the token. How did the service worker get the custom token from the functions server?

Yes. This token is generated client side via the Firebase API [`getIdToken()`](https://firebase.google.com/docs/reference/js/firebase.User#getidtoken).

Service worker is the one passing passing the token to your server and not the other way around.

I see that Firebase docs has recently published a service worker auth tutorial [here](https://firebase.google.com/docs/auth/web/service-worker-sessions#web-v8_1). They have a very detailed explanation on how everything is architected.

Note that you don't know to follow the service worker and client side changes section there as my addon does that already for you.

**Comment by mamiller93** [comment]
> > When a user loads the page for the first time, they won't be authenticated and fastboot will agree.
> 
> Yes
> 
> > When the user signs in for the first time, that request goes directly to firebase.auth() to be authenticated.
> 
> Yes, and to be specific, the `firebase.auth()` of the client itself, not the server.
> 
> > If the user refreshes the page, the service worker that is registered updates the fetch request with the token. How did the service worker get the custom token from the functions server?
> 
> Yes. This token is generated client side via the Firebase API [`getIdToken()`](https://firebase.google.com/docs/reference/js/firebase.User#getidtoken).
> 
> Service worker is the one passing passing the token to your server and not the other way around.
> 
> I see that Firebase docs has recently published a service worker auth tutorial [here](https://firebase.google.com/docs/auth/web/service-worker-sessions#web-v8_1). They have a very detailed explanation on how everything is architected.
> 
> Note that you don't know to follow the service worker and client side changes section there as my addon does that already for you.

Right. In my case, it goes directly to Firebase Auth (`google.com/<something>`) for authentication. Or the emulator if running locally.

Originally, I didn't have any service worker code but eventually I copied your adapter to debug the service worker. I don't see the service worker sending anything directly to `localhost:5001`, the `Host:Port` of my functions 'server'. How exactly does the service worker pass the token to my 'server' if I'm using Firebase as my serverless architecture? Firebase's tutorial also describes a server side express sample. I must be missing something logically here!

**Comment by mikkopaderes** [comment]
Hmm, I think the emulator is the problem. Are you serving your app in the firebase emulator or are you accessing it from `ember serve` which defaults to localhost:4200?

**Comment by mamiller93** [comment]
I'm accessing it from `ember serve` at `localhost:4200`. Should I be serving the entire ember app from the cloud function such that the "main" app is really the cloud function? I figured the fastboot app server hooked into the already-running ember server.

**Comment by mikkopaderes** [comment]
Yes, that's correct. If you do it in `ember serve` then that means it's running in its own fastboot server under 4200 port. Hence the token is being sent to the builtin local fastboot server for 4200 and not to the 5001 server.

**Comment by mamiller93** [comment]
Iiiiiiinteresting. So the guide was describing adding the adapters, serializers, server workers etc to an existing ember app. And then the expectation is to wrap that ember app inside of a firebase function? Then hit `localhost:5100` in my browser. 

I definitely didn't understand that from the guides. I thought there were two concurrent servers running, one ember one firebase functions. Iiiiiiiinteresting. Alright, I'll give it all a go later today to wrap my current ember app inside the firebase function. Unless you have an example already I could look at? 

Regardless thank you for helping and filling in the gaps!

**Comment by mikkopaderes** [comment]
Yes, but it's not necessarily a Firebase Function. But yeah, part of Fastboot setup is that you will have to setup your own server that will prerender your Ember App. The token will be sent to the server that specifically served the Ember App.

The example in my guide is also a lowkey guide to server a Fastboot app inside a Firebase Funxtion. It make use of the [fastboot-express-middleware](https://github.com/ember-fastboot/ember-cli-fastboot/tree/master/packages/fastboot-express-middleware) instead of the [fastboot-app-server](https://github.com/ember-fastboot/ember-cli-fastboot/tree/master/packages/fastboot-app-server).
