### ISSUE TITLE
Peer dependency problems

### ISSUE THREAD

**Issue by roomman** [mikkopaderes/ember-cloud-firestore-adapter#165]
Hi @mikkopaderes and thanks for this project, it's been a blessing!

Our app has been running nicely with the current version of the add-on for months. For whatever reason, we've ended up with ember-firebase-service@9.0.1 installed as a dev dependency. That's not been a problem until today, when I tried to test the app against the latest version of Ember, via ember-try. When I did, it refused to play ball because your add-on has ember-firebase-service@8.0.0 as a peer dependency. I tried rolling back to that version but that broke the app - auth doesn't appear to be working properly and that's preventing the adaptor resolving requests 😢

Currently, the only way I can get the app working is with @9.0.1 as a dev dependency. 

Before I throw myself into another day of debugging, is there a rationale for having the legacy dependency as a peer? I note that @9.0.1 is in your own dev dependencies, so it seems odd at first glance. 

Any context / thoughts would be greatly appreciated 👍🏻

**Comment by roomman** [comment]
Great, many thanks for confirming 👍🏻

**Comment by mikkopaderes** [comment]
Resolved by #167
