### ISSUE TITLE
Ember tests are failing following upgrade

### ISSUE THREAD

**Issue by roomman** [mikkopaderes/ember-cloud-firestore-adapter#166]
Hello! I'm attempting to upgrade one of our apps to Ember 3.26. The app itself seems to work okay but I am encountering some new errors that seem to be related to this add-on. For example, this test:

```
import { module, test } from 'qunit';
import { setupRenderingTest } from 'ember-qunit';
import { render } from '@ember/test-helpers';
import { hbs } from 'ember-cli-htmlbars';

module('Integration | Component | video-list-item', function (hooks) {
  setupRenderingTest(hooks);

  hooks.beforeEach(async function () {
    await this.owner
      .lookup('service:session')
      .authenticate('authenticator:oneday-firebase', (auth) => {
        return auth.signInWithEmailAndPassword(email, password);
      });
  });

  hooks.afterEach(async function () {
    await this.owner.lookup('service:session').invalidate();
  });

  test('it renders', async function (assert) {
    let store = this.owner.lookup('service:store');
    const video = await store.findRecord('video', '7Qdgy5xYVOErF86idWaz');
    this.set('video', video);

    await render(hbs`<VideoListItem @video={{this.video}} @index=1 />`);

    assert.dom('[data-test-video-list-item]').exists();
  });
});
```
Results in the following error, which I was not seeing prior to the upgrade:
```
Uncaught (in promise) Error: endAsync called with no preceding beginAsync call.
```

The above error is accompanied by the following warning:
```
WARNING: Async Request leaks detected. Add a breakpoint here and set `store.generateStackTracesForTrackedRequests = true;`to inspect traces for leak origins:
	 - DS: Handle Adapter#findHasMany of 'video' : 'stage'
	 - DS: Handle Adapter#findHasMany of 'video' : 'subject'
```
The component itself is pretty simple. The template renders some details of the Video model it is handed. This includes listing out the titles of any related Stages and Subjects. The model definition looks like this:

```
import Model, { attr, hasMany } from '@ember-data/model';

export default class VideoModel extends Model {
  @attr('string') title;

  @hasMany('stage', {
    isRealtime: true,
  })
  stages;

  @hasMany('subject', {
    isRealtime: true,
  })
  subjects;

  get heading1() {
    return this.title;
  }
}
```
What appears to be happening is that Ember Data is loading the relationships asynchronously and Ember's testing tools are not happy about it. I understand why, but I don't know what alternative strategy I could use.  

I had a good chat with a colleague, his reaction was "why don't you just stub out the store and mock some data?" For the test above, that would be fine, but I have an acceptance test that gets the same errors and warnings:
```
import { module, test } from 'qunit';
import { visit, currentURL } from '@ember/test-helpers';
import { setupApplicationTest } from 'ember-qunit';

module('Acceptance | user can view list of videos', function (hooks) {
  setupApplicationTest(hooks);

  hooks.beforeEach(async function () {
    await this.owner
      .lookup('service:session')
      .authenticate('authenticator:oneday-firebase', (auth) => {
        return auth.signInWithEmailAndPassword(email, password);
      });
  });

  hooks.afterEach(async function () {
    await this.owner.lookup('service:session').invalidate();
  });

  test('visiting /videos', async function (assert) {
    await visit('/videos');
    assert.equal(currentURL(), '/videos', 'the videos route can be accessed');
    assert.dom('[data-test-simple-filter]').exists('the filter tools exist');
    assert.dom('[data-test-video-list]').exists('the list of videos exist');
  });
});
```
The Route being accessed by this acceptance test makes the following requests to the Store:
```
import Route from '@ember/routing/route';
import { inject as service } from '@ember/service';
 
export default class VideoRoute extends Route {
 @service store;
 
 async model() {
   const videos = await this.store.findAll('video', { reload: true });
   const model = videos.filter((v) => !!v.published);
   await this.store.findAll('stage', { reload: true });
   await this.store.findAll('subject', { reload: true });
   return model;
 }
}
```
Implicitly, this is testing that a) a user can authenticate via the Auth emulator, b) a request made by that user passes the Firebase security rules, c) the Firestore emulator returns what we need for rendering in the app, d) the relevant bits get rendered in the DOM. If I were to stub all that out, I'm not sure how valid that test would be. I certainly couldn't use it in a CI context.

This leaves me wondering how others are testing their Ember apps using this add-on, using the Firebase Emulator suite? Are there other strategies that I should be considering? Are there obvious problems with the tests I've included above that could be addressed? Do I need to use Ember testing for basic render testing and something else for end-to-end tests and CI integration? I'm I naive to think I can get end-to-end tests working in this way?

Any and all feedback is extremely welcome. Thanks!

**Comment by roomman** [comment]
**Update**: I've just been playing around with the failing tests and discover that adding `settled()` from `@ember/test-helpers`, after each of the session methods, kills the `endAsync called with no preceding beginAsync call` error:
```
import { module, test } from 'qunit';
import { setupRenderingTest } from 'ember-qunit';
import { render, settled } from '@ember/test-helpers';
import { hbs } from 'ember-cli-htmlbars';

module('Integration | Component | video-list-item', function (hooks) {
  setupRenderingTest(hooks);

  hooks.beforeEach(async function () {
    await this.owner
      .lookup('service:session')
      .authenticate('authenticator:oneday-firebase', (auth) => {
        return auth.signInWithEmailAndPassword('simon@mysolomon.co.uk', 'password');
      });
    await settled();
  });

  hooks.afterEach(async function () {
    await this.owner.lookup('service:session').invalidate();
    await settled();
  });

  test('it renders', async function (assert) {
    let store = this.owner.lookup('service:store');
    const video = await store.findRecord('video', '7Qdgy5xYVOErF86idWaz');
    this.set('video', video);

    await render(hbs`<VideoListItem @video={{this.video}} @index=1 />`);

    assert.dom('[data-test-video-list-item]').exists();
  });
});
```
I'm still getting warnings about `Async Request leaks detected` relating to the adapter, but the error must be `ember-simple-auth` related?

**Comment by mikkopaderes** [comment]
Hmm, I haven't tried the latest Ember version yet. But if this is related to authentication, perhaps you could try stubbing the auth rather than actually signing in? Something like this perhaps..

```javascript
const session = this.owner.lookup('service:session');

session.isAuthenticated = true;
session.data = {
  authenticated: {
    user: {
      uid: 'test_uid',
      displayName: 'test_display_name',
      photoURL: 'test_photo_url',
    },
  },
};
```

**Comment by roomman** [comment]
Hi Mike and many thanks for coming back to me. I think you've gone right to the root of my issue - whether it's feasible to expect to be able to run end-to-end (auth, adapter, firebase rules, rendering and user interaction) acceptance tests.

Stubbing the auth service works, but only for testing the app in isolation. Without the full Firebase auth object I can't get past the security rules, to get the models I need to be able to test that a user can do what I need them to.

I've found some work arounds that are good for me. My question is, more generally, do you to end-to-end acceptance testing in your own apps (when using this add-on) and if so, can you share any best practices?

**Comment by mikkopaderes** [comment]
Yes, I do end-to-end testing but without the authentication. I didn't find any use to emulate it because I have a different project to test my security rules for me.

But I'm not saying that mine is a good practice. I just do it that way.
