### ISSUE TITLE
FirebaseAuthenticator: onAuthStateChanged User object is occasionally null when multiple tabs open

### ISSUE THREAD

**Issue by charlesfries** [mikkopaderes/ember-cloud-firestore-adapter#168]
I've found that the User object passed by `onAuthStateChanged()` in the `restore()` method of `FirebaseAuthenticator` is sometimes null when multiple instances of the Ember app are running.

Steps to recreate:

- Open two instances of your app (can be multiple tabs or multiple windows)
- Log the session data object in the post-authentication route
- Sign in on the first tab:
```javascript
await this.session.authenticate('authenticator:firebase', (auth) => {
  return auth.signInWithEmailAndPassword(email, password);
});
```
- Visit the second tab

This screenshot is from the second tab after logging into the first:

![firebase](https://user-images.githubusercontent.com/2275005/119401089-e0a22500-bc8f-11eb-8301-1b75816f1100.png)

It seems to be some sort of timing issue. Logging `this.session.data.authenticated.user` in the immediate post-authentication route produces `null` about half of the time. I can then refresh the page, and then the `restore()` method is able to find the session data (and the user object) again.

![firebase2](https://user-images.githubusercontent.com/2275005/119400912-a6d11e80-bc8f-11eb-8da8-8cda1307dc8f.png)

Any ideas?

**Comment by mikkopaderes** [comment]
Have you tried to see if it's the same case for regular Firebase auth (without this addon)? This might be out of my control if so..

**Comment by charlesfries** [comment]
I'll give that a shot
