### ISSUE TITLE
Unexpected behaviour when loading relationships

### ISSUE THREAD

**Issue by roomman** [mikkopaderes/ember-cloud-firestore-adapter#176]
Hi @mikkopaderes, I'm having a few issues loading records with a hasMany relationship. I have some `customers` that can have many `bookings`. As per the docs, a reference to each root-level booking is stored in each customer's sub-collection.

When I `store.findAll('booking', {})` I get all bookings and if I subsequently run `customer.bookings.toArray()` I can see the relevant records for that one customer. However, if I skip the first step (i.e. I don't load all bookings first) the second query returns an empty array.

I'm I missing something, or assuming a behaviour that's not in your design?

**Comment by mikkopaderes** [comment]
I understand your problems correctly, then this is expected and is how Ember Data works.

When you do `findAll` this caches the data within that session so that any other calls that that will reference the data cached from `findAll` will contain records already.

If you skip `findAll`, you have to do `customer.get('bookings').then((records) => ...)` or `customer.books.then((records) => ...)` if Ember Data allows this already.

**Comment by roomman** [comment]
Thanks for getting back to me. 

I'm inside an async model hook, in one of my routes:
```
import Route from '@ember/routing/route';
import { inject as service } from '@ember/service';

export default class AuthenticatedUserBookingsRoute extends Route {
  @service store;

  @service currentUser;

  async model() {
    // await this.store.findAll('booking', {});
    const customer = this.currentUser.user.customer.content;
    const bookings = await customer.get('bookings');
    return bookings.toArray();
   }
}
```
In the above example, the customer has some bookings referenced in their sub-collection but `bookings.toArray()` is empty. However, if I uncommented `await this.store.findAll...` the array contains the bookings.

Naturally, given the Firebase pricing model, I'm keen to avoid expensive calls to get all bookings from the database. I know I could use `query` but the above approach just feels more natural. Am I being too naive?

**Comment by mikkopaderes** [comment]
Have you checked what the contents are for `booking`, not after the `.toArray()`?

**Comment by roomman** [comment]
Yes, when I inspect bookings, I see this Class with an `_length` of zero.

<img width="1429" alt="Screenshot 2021-08-22 at 15 45 25" src="https://user-images.githubusercontent.com/10168451/130359387-dde99889-0186-422f-bad1-8ca4a1d87d81.png">

If I run `await this.store.findAll('booking'...`, I see a `_length` of one, which is the correct number of bookings for that customer.

<img width="1425" alt="Screenshot 2021-08-22 at 15 47 45" src="https://user-images.githubusercontent.com/10168451/130359499-86536aea-fe95-4edf-ac78-2ac8e6e658bc.png">

I tried adding `{ async: true }` as an option to `@hasMany` in the customer's model definition but that's not done a thing:

```
  @hasMany('booking', {
    isRealtime: true,
    async: true,
  })
  bookings;
```

**Comment by mikkopaderes** [comment]
How are you setting up your relationship in your Models? Can you show it to me? If this is a simple `one-to-many` then it should work as-is provided that the `customer` is stored like this in the `booking`

```json
"booking": {
  "id": <...>,
  "customer": /customers/<customer_id>
}
```

**Comment by roomman** [comment]
The Ember models are defined like so:

```
import Model, { hasMany } from '@ember-data/model';

export default class CustomerModel extends Model {
  ...

  @hasMany('booking', {
    isRealtime: true,
  })
  bookings;

  ...
}
```

```
import Model, { belongsTo } from '@ember-data/model';

export default class BookingModel extends Model {
  ...

  @belongsTo('customer', {
    isRealtime: true,
  })
  customer;

  ...
}

```

Persistence is the Firestore looks like this:

```
customers (collection):
   customer1:
      bookings (sub-collection):
         booking1: 
            referenceTo: bookings/booking1

bookings (collection):
   booking1:
      customer: customers/customer1
```

Thanks for your time @mikkopaderes, it's greatly appreciated. 👍🏻

**Comment by mikkopaderes** [comment]
First thing I noticed is you don't need to manage a sub collection in the customer side if it's a one-to-many relationship. But I don't think that this has anything to do with your problem.

One thing you could try to rule out if is the security rules are messing with your code.

The problem is interesting because this is such a simple use-case which is tested to work. If you're still having issue, then I'll try to replicate on my side.

**Comment by roomman** [comment]
Hi @mikkopaderes, after a bit of playing around it transpires that you can do this:
```
async model() {
   const customer = await this.currentUser.user.get('customer');
   let bookings = await customer.get('bookings');
   bookings = bookings.toArray();
   return bookings;
}
```
But you can't do this:
```
async model() {
   let bookings = await this.currentUser.user.customer.get('bookings');
   bookings = bookings.toArray();
   return bookings.toArray();
}
```
So, each step in chain needs to fully resolve before the next can do its stuff. I guess that's pretty logical.

Good note on the one-to-many, thanks.

Thanks again for your time and help. 👍🏻

**Comment by mikkopaderes** [comment]
Awesome! Happy that you've solved your issue.
