### ISSUE TITLE
Issue with tests after installing this and peer dependencies

### ISSUE THREAD

**Issue by dknutsen** [mikkopaderes/ember-cloud-firestore-adapter#177]
Hello! Thanks again for a great addon. I've been adding some tests in an app and realized that they're all breaking in the firebase initializer for some reason. At first I thought it was my code but I managed to create [a minimal reproduction repo](https://github.com/dknutsen/ecfa-reproduction) with the following steps:
- create a new ember app
- add a stub component and component test, run tests, all pass
- add ember-cloud-firestore-adapter and peer dependencies ([this commit](https://github.com/dknutsen/ecfa-reproduction/commit/e8986ea3b36b3c5ec48f72bf3a3a8958e0b09adf))
- the integration test (and any other tests) now fails with the following:
```
not ok 1 Chrome 92.0 - [243 ms] - Integration | Component | something: it renders
    ---
        actual: >
            null
        stack: >
            TypeError: Cannot convert undefined or null to object
                at hasOwnProperty (<anonymous>)
                at http://localhost:7357/assets/vendor.js:69452:273109
                at Sp.dp (http://localhost:7357/assets/vendor.js:69452:273263)
                at new Sp (http://localhost:7357/assets/vendor.js:69452:279707)
                at ym.instanceFactory (http://localhost:7357/assets/vendor.js:69452:336579)
                at C.getOrInitializeService (http://localhost:7357/assets/vendor.js:349:10320)
                at C.getImmediate (http://localhost:7357/assets/vendor.js:349:7312)
                at $._getService (http://localhost:7357/assets/vendor.js:349:16917)
                at $.n.type.a.<computed> [as firestore] (http://localhost:7357/assets/vendor.js:349:19680)
                at Object.initialize (http://localhost:7357/assets/vendor.js:99326:25)
        message: >
            Promise rejected before "it renders": Cannot convert undefined or null to object
```

Any idea what might be going on? Maybe I got some versions wrong or just missed something?

**Comment by mikkopaderes** [comment]
You need to set the `firebase` settings in your config environment. See [here](https://github.com/mikkopaderes/ember-cloud-firestore-adapter/blob/master/docs/getting-started.md#1-setup-firebase-and-addon-configuration).

**Comment by dknutsen** [comment]
🤦‍♂️ of course. I had it all set in my app just not in the testing environment. 

Would you be open to adding some asserts in [the service](https://github.com/mikkopaderes/ember-firebase-service/blob/master/addon/services/firebase.ts) to make sure the config is there before initializing firebase? Might make things easier to debug for people like me being dumb 😅 Happy to open a PR if that would be helpful.

**Comment by mikkopaderes** [comment]
That's sounds like an awesome idea. Happy to accept the PR 😄

**Comment by mikkopaderes** [comment]
On second thought. I have some changes going on with supporting Firebase 9 and it might change where the config gets used so I'll make sure to do this for that change.

**Comment by dknutsen** [comment]
Oh whoops ha just saw your second comment. Feel free to do whatever with the PR 😁
