### ISSUE TITLE
Possible typo in the testing doc

### ISSUE THREAD

**Issue by charlesfries** [mikkopaderes/ember-cloud-firestore-adapter#183]
https://github.com/mikkopaderes/ember-cloud-firestore-adapter/blob/master/docs/testing.md

It seems like

```
if (environment === 'production') {
  ENV['ember-cloud-firestore-adapter'] = null;
}
```

will overwrite the Firebase configuration, now that `firebaseConfig` is embedded in `ENV['ember-cloud-firestore-adapter']`.

**Comment by mikkopaderes** [comment]
You're right. Thanks for pointing that out!
