### ISSUE TITLE
ember-cli-fastboot not resolvable

### ISSUE THREAD

**Issue by mandi05** [mikkopaderes/ember-cloud-firestore-adapter#189]
Hi,

Thank you for your recent release.

I've been trying to get a running clean ember app, but I keep getting this error message on the build.

`ember-cloud-firestore-adapter tried to import "ember-cli-fastboot" but the package was not resolvable from <path>/node_modules/ember-cloud-firestore-adapter`

I installed the peerDependencies and `ember install ember-cloud-firestore-adapter`.

Not sure if I'm missing anything.

**Comment by mikkopaderes** [comment]
That's odd. I just did a clean install and things seems fine. Do you have a test repo I could pull to check?

**Comment by mikkopaderes** [comment]
Nevermind, I tested the package with `npm link` where it wasn't failing. Doing a fresh `npm install` with the `2.0.0` version is breaking the build. Thanks for the report, will look into it ASAP!
