### ISSUE TITLE
v2 SW error: `Failed to execute 'importScripts' on 'WorkerGlobalScope'`

### ISSUE THREAD

**Issue by charlesfries** [mikkopaderes/ember-cloud-firestore-adapter#192]
```
Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at 'https://www.gstatic.com/firebasejs/9.0.2/firebase-app.js' failed to load.
```

![import scripts](https://user-images.githubusercontent.com/2275005/135681571-8099d9c3-17b9-4e2c-8ce0-f7b99db0b837.png)

I'm seeing this service worker error after the ECFA v2 update. 

Steps to reproduce:

```
ember new my-app
cd my-app

ember install ember-simple-auth firebase ember-cloud-firestore-adapter ember-service-worker

ember generate adapter application
ember generate serializer application

// add config

ember s
```

I believe this may have to do with `ember-service-worker` wrapping the contents of `sw.js` in a self invoking function, in which case this issue is unrelated to this addon.

```
DEBUG: -------------------------------
DEBUG: Ember      : 3.28.1
DEBUG: Ember Data : 3.28.3
DEBUG: -------------------------------
```

**Comment by charlesfries** [comment]
Actually this could be due to how Firebase modules are imported into the SW in v9: https://firebase.google.com/docs/cloud-messaging/js/receive#setting_notification_options_in_the_service_worker

I tried swapping the `importScript` calls for ESM imports but I don't think `ember-service-worker` is going to be able to resolve anything unless we 1) bundle `firebase-app` and `firebase-auth` separately in the dist and import them into the SW, or 2 ) use fully qualified URLs.

**Comment by mikkopaderes** [comment]
Yeah, you're right. Thanks for catching this.

What we want to happen to quickly make this work is to `importScript` the `firebase-app-compat.js` and `firebase-auth-compat.js`. I can quickly make that change and release a fix to get it going but as with the other goals, long term is to slowly move away from compat SDK.
