### ISSUE TITLE
Timestamp attrs not serialized correctly after save

### ISSUE THREAD

**Issue by charlesfries** [mikkopaderes/ember-cloud-firestore-adapter#198]
Attributes of transform type `timestamp` seem to deserialize to Firestore timestamp objects after the first save.

```
DEBUG: -------------------------------
DEBUG: Ember      : 3.28.1
DEBUG: Ember Data : 3.28.3
DEBUG: -------------------------------
```

Repro:

```
ember new my-app &&
cd my-app &&
ember install ember-simple-auth ember-cloud-firestore-adapter firebase &&
ember g adapter application &&
ember g serializer application &&
ember g route application &&
ember g model post
```

Update config, adapter, serializer

```
app/models/post.js

import Model, { attr } from '@ember-data/model';

export default class PostModel extends Model {
  @attr('timestamp') createdAt;
  @attr('string') title;
}
```

```
app/routes/application.js

import Route from '@ember/routing/route';

export default class ApplicationRoute extends Route {
  model() {
    const post = this.store.createRecord('post', {
      title: 'My Title',
    });
    return post.save();
  }
}
```

Running the above code yields the correct record data in Cloud Firestore, but the `createdAt` attr appears locally as a timestamp object instead of a date value--

![image](https://user-images.githubusercontent.com/2275005/136247877-83c31556-8a3f-47a2-8636-072003feb5ba.png)

For the time being I get around this by calling `this.post.reload()` right after `this.post.save()` to get the proper deserialized value.

FYI I can submit a PR for this, I just don't know exactly where things are going wrong.

**Comment by mikkopaderes** [comment]
This is expected as we don't know from the client side what timestamp this will yield from the Firebase server. You either have to make the record realtime so it immediately resolves to the timestamp or for initial create, you manually show the current timestamp in your UI that's not dependent on the record timestamp.
