### ISSUE TITLE
any way to combine hasMany fetch request?

### ISSUE THREAD

**Issue by masato-io** [mikkopaderes/ember-cloud-firestore-adapter#208]
I'm new to ember-data & firestore world so apology for newbie question in advance. Lets say I have:

// models/post.js
```js
@hasMany("comment") comments;
```

// models/comments.js
```js
@belongsTo("post") post;
```

and when I reference the property comments somewhere in the template, it will fetch the related comments of the post one-by-one in separate requests which results in many requests.

I believe this is usually managed by `coalesceFindRequests` switch in other adapter but was wondering if there is a way to reduce requests in `ember-cloud-firestore-adapter`. Please let me know if I'm missing something obvious, your input would be appreciated :)

**Comment by mikkopaderes** [comment]
What happens here behind the scenes is that it will fetch all comments in one go but will do a `store.findRecord` behind to scenes to reuse all necessary logic to properly store them in `Store` service. But those extra `store.findRecord` doesn't really make a request to Firestore, it will just fetch things from cache of the previous fetch all comments.

**Comment by charlesfries** [comment]
@mikkopaderes I believe I am seeing the same behavior--fetching a `@hasMany` with 10 related records will always yield ~11 requests. I'll see if I can make a repro

I'm using this hacky-ish code for the time being. There are some quirks related to subcollections not updating, but if you aren't using subcollections heavily this override should be suitable:

```js
findHasMany(store, snapshot, url, relationship) {
  return new RSVP.Promise((resolve, reject) => {
    const collectionRef = this.buildHasManyCollectionRef(store, snapshot, url, relationship);
    collectionRef
      .get()
      .then((querySnapshot) => {
        resolve(
          querySnapshot.docs.map((docSnapshot) => {
            return Object.assign(docSnapshot.data(), { id: docSnapshot.id });
          })
        );
      })
      .catch(reject);
  });
}
```

**Comment by masato-io** [comment]
Thank you for your responses @mikkopaderes @charlesfries  :) 

I think what I was wondering was if there is similar way to accomplish side loading as below:

```js
model() {
  return this.store.findAll('post', { include: 'comment' });
}
```

so that when template renders posts with loop, it won't fetch all related comments one by one (same problem described [here](https://embermap.com/topics/data-loading/setting-up)).

what @charlesfries described seems like what I'm looking for, thank you for the suggestion, I'll give it a try!

**Comment by mikkopaderes** [comment]
> Thank you for your responses @mikkopaderes @charlesfries :)
> 
> I think what I was wondering was if there is similar way to accomplish side loading as below:
> 
> ```js
> model() {
>   return this.store.findAll('post', { include: 'comment' });
> }
> ```
> 
> so that when template renders posts with loop, it won't fetch all related comments one by one (same problem described [here](https://embermap.com/topics/data-loading/setting-up)).
> 
> what @charlesfries described seems like what I'm looking for, thank you for the suggestion, I'll give it a try!

No, the adapter doesn't support that. That feature is also something exclusive for `JSONAPIAdapter` and to a backend that adheres to [jsonapi](https://jsonapi.org/) specs.

**Comment by mikkopaderes** [comment]
> @mikkopaderes I believe I am seeing the same behavior--fetching a `@hasMany` with 10 related records will always yield ~11 requests. I'll see if I can make a repro
> 
> I'm using this hacky-ish code for the time being. There are some quirks related to subcollections not updating, but if you aren't using subcollections heavily this override should be okay:
> 
> ```js
> findHasMany(store, snapshot, url, relationship) {
>   return new RSVP.Promise((resolve, reject) => {
>     const collectionRef = this.buildHasManyCollectionRef(store, snapshot, url, relationship);
>     collectionRef
>       .get()
>       .then((querySnapshot) => {
>         resolve(
>           querySnapshot.docs.map((docSnapshot) => {
>             return Object.assign(docSnapshot.data(), { id: docSnapshot.id });
>           })
>         );
>       })
>       .catch(reject);
>   });
> }
> ```

Hmm, it's been a long time since I've touched that section of the code. Maybe the behavior of Firestore has changed. Basically I try to fetch the `hasMany` first via the `onSnapshot` API. The way it works is that if you're already listening for realtime changes on a record, if you fetch it again, it will get it from the cache. It's why I have the `onSnapshot` [here](https://github.com/mikkopaderes/ember-cloud-firestore-adapter/blob/master/addon/adapters/cloud-firestore-modular.ts#L224).

Or maybe you have `hasMany` set to `isRealtime = true`. If that's the case, I do think it's going to make extra requests per every record just to setup the listeners.

**Comment by masato-io** [comment]
Thank you for all the answers, it was very helpful for me. For now since my original question is resolved, I feel this issue can be closed. Maybe reopen it if there is still relevant conversation on this :)
