### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by charlesfries** [mikkopaderes/ember-cloud-firestore-adapter#231]
Hello @mikkopaderes, would it be possible to cut a release in the not too distant future? I need that `ember-classic-decorator` deletion so I can get rid of a few Ember global deprecation warnings. Thank you!

Changelog:

- Upgrade Ember CLI to 3.28.5 (#217)
- Fix acceptance test for query (#218)
- Fix lint warning (#219)
- Fix working but improper import (#220)
- Removed unused hasMany (#223)
- QUnit equal -> strictEqual (#222)
- Bump firebase and firebase-tools version (#227)
- Remove auto generated files from repo (#228)

**Comment by mikkopaderes** [comment]
Release in `2.2.0`
