### ISSUE TITLE
Deserialize an array of references

### ISSUE THREAD

**Issue by bagby** [mikkopaderes/ember-cloud-firestore-adapter#233]
Suppose I have a firestore field that is an array of references, for example in a `post` document I have a `comments` field:

<img width="570" alt="Screen Shot 2022-01-27 at 11 09 03 AM" src="https://user-images.githubusercontent.com/176297/151397512-f9fd59a3-d338-4b96-86a9-2c0c6491185c.png">

In my Ember data model I can't simply do 
```
@hasMany('comment') comments;
```
because that's not how this adapter works, it expects the `comment` document to have a `@belongsTo` reference to the `post`. I'm thinking that a custom transform is needed, like a `docref-array` or something, but before I dive into that I wanted to check and see if there's an easier way to do this using this adapter, or if anyone has suggestions as to how this might be accomplished.

**Comment by mikkopaderes** [comment]
I don't think hasMany would work for your case if you store it in an array. In fact, I would advise you not to do so.

In your example, comments in a post could be an infinite amount. If you don't store it in a sub-collection then every time you fetch your post, it will include the comment references. That could be potentially slow down your app and cause your billings to spike as well because of the size of the response.

**Comment by bagby** [comment]
🤦 

Putting ids in a subcollection just works™.

`@hasMany('post', { inverse: null }) topPosts;`

`dailyDashboard.topPosts` gives me what I need. Thank you 👍

**Comment by mikkopaderes** [comment]
I mean it depends on your use-case. If you want to model it where topPosts is a hasMany, then it's something that's lazily loaded so it should be in a sub-collection to match that behavior. 

If you're taking the hasMany approach, you can either set an attribute referenceTo to the corresponding post doc or your duplicate the post data itself to the topPosts sub-collection.

**Comment by bagby** [comment]
You are indeed correct, I needed to add the `referenceTo` field to the sub collection doc. Now everything resolves beautifully 🎉 Thanks again.
