### ISSUE TITLE
Adding model @attr options in Typescript projects

### ISSUE THREAD

**Issue by roomman** [mikkopaderes/ember-cloud-firestore-adapter#249]
@mikkopaderes did you find a solution to this? -https://github.com/mikkopaderes/ember-cloud-firestore-adapter/blob/9f584e53d90269ae3559c11eae0695fbee60d91b/tests/dummy/app/models/group.ts#L25

I'm seeing errors wherever I use the `isRealtime` option in TS Model definitions, and was hoping to avoid `@ts-ignore`.

**Comment by mikkopaderes** [comment]
No, I have not as of the moment. I would've loved for the type of ember-data relationships to have catch all properties but it just isn't like that at the moment.

**Comment by charlesfries** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/64993

**Comment by roomman** [comment]
Thanks @charlesfries, updating to the latest **ember-data** types closes this issue.
