### ISSUE TITLE
Not able to find record with `query`

### ISSUE THREAD

**Issue by knownasilya** [mikkopaderes/ember-cloud-firestore-adapter#251]
I'm migrating from emberfire (beta)

**Describe the bug**

Querying like so: 

```ts
const accounts = await this.dataStore.query('account', {
      isRealtime: true,
      queryId: 'account',
      filter: (ref: any) => {
        return query(
          ref,
          where('username', '==', username.toLowerCase()),
          limit(1)
        );
      },
    });
const account = accounts.objectAt(0);
```

Resulting `account` is undefined. This worked with similar syntax in emberfire. The records are simple in this case.

Console says this before the query not found:

> @firebase/firestore: Firestore (9.13.0): Could not reach Cloud Firestore backend. Connection failed 1 times. Most recent error: FirebaseError: [code=unavailable]: The operation could not be completed
This typically indicates that your device does not have a healthy Internet connection at the moment. The client will operate in offline mode until it is able to successfully connect to the backend.

**Expected behavior**
Expecting an account returned.

**Tooling versions (please complete the following information):**
 - Ember: ^3.28.10
 - Ember Data: ^3.28.12
 - Firebase: ^9.13.0

**Comment by knownasilya** [comment]
Ah, I had the emulator config. Might be worth having that commented out in the docs?

**Comment by mikkopaderes** [comment]
I have it in docs to disable it in production [here](https://github.com/mikkopaderes/ember-cloud-firestore-adapter/blob/master/docs/testing.md#setup-addon-to-use-emulator)

**Comment by knownasilya** [comment]
Hum, might not be worth showing in getting started?
