### ISSUE TITLE
Creating records with custom id

### ISSUE THREAD

**Issue by knownasilya** [mikkopaderes/ember-cloud-firestore-adapter#255]
Is there a way to do this? If not, this is a request for that 😄

**Comment by charlesfries** [comment]
You should be able to either pass in `id` to `createRecord()` or override `generateIdForRecord` if you have a specific format you want to use:

```js
// app/adapters/application.js

generateIdForRecord(store, type): string {
  const id = super.generateIdForRecord(store, type);
  return `${type.substring(0, 3)}_${id}`;
}
```

**Comment by knownasilya** [comment]
I tried passing id, and that didn't create the record. Maybe there was some other issue. Will try again later.

**Comment by knownasilya** [comment]
It does work, 🤷🏼  seems like I had something else going on before.
