### ISSUE TITLE
Functions emulator and fastboot imports

### ISSUE THREAD

**Issue by knownasilya** [mikkopaderes/ember-cloud-firestore-adapter#273]
One of the missing pieces is setup for function emulator and fastbootable imports for the functions module. Is this something that you'd merge?

**Comment by mikkopaderes** [comment]
What's the use-case for `function`? It's a backend thing and not interfaced in the frontend, right?

**Comment by mikkopaderes** [comment]
Ah, I see, I never used it before but there's an [API in JS SDK client](https://firebase.google.com/docs/reference/js/functions) for it.

**Comment by knownasilya** [comment]
would be nice if configuring functions for emulator worked the same as firestore and auth. Also storage too.

**Comment by charlesfries** [comment]
@knownasilya Mind clarifying? Are you referring to the options obj that can be passed?

**Comment by knownasilya** [comment]
`config.environment.js`

```js
ENV['ember-cloud-firestore-adapter'].functions = {
      emulator: {
        hostname: 'localhost',
        port: 5001,
      },
    };
```

**Comment by knownasilya** [comment]
Submitted a pr
