### ISSUE TITLE
Many to many Stored in Subcollection

### ISSUE THREAD

**Issue by lukaiser** [mikkopaderes/ember-cloud-firestore-adapter#71]
Thanks for the grate work!
I was wondering if there is a reason that many to many references are stored in a subcollection and not an array? This is costs time and money as a lot more documents need to be read.

Thanks for the feedback!

**Comment by rmmmp** [comment]
For scalability. We lazy load the array as we're not sure how big it's going to be.

**Comment by lukaiser** [comment]
I get that. But what if I want to restrict it anyway and therefore can guarantee that I won't be many?
Would a relationship option be an option? So that you can opt in to array-saving?

**Comment by rmmmp** [comment]
Maybe just store it as an array not a relationship. Is that viable for your case?

**Comment by rmmmp** [comment]
Also, another benefit of putting it in subcollection is you can make limit the amount you're looking for.

**Comment by lukaiser** [comment]
In that case it is not. But it isn't a big deal either how it is currently stored.
Would you be open for the option to save it differently? The current way would be default, but if you add an option it would be stored in an array? Something like:

`DS.hasMany('folder', { storedInArray: true })`

**Comment by rmmmp** [comment]
You can save it as an array by simply using `DS.attr()`. Does that work for your case?

**Comment by mikkopaderes** [comment]
Stale issue
