### ISSUE TITLE
Is there a way to Enable offline data

### ISSUE THREAD

**Issue by alexmasita** [mikkopaderes/ember-cloud-firestore-adapter#79]
As seen on the official docs, Cloud firestore enables you to use the cache when you loose the internet connection so that the app does not break.  Is there an easy way to configure this here?  

You can check out the article here: [firestore enable persistence link](https://firebase.google.com/docs/firestore/manage-data/enable-offline?authuser=0)

It would be great to be able to easily manually disable and enable network access programmatically as seen on that page as well.

Thank you.

**Comment by mikkopaderes** [comment]
You can inject the `firebase` service and setup whatever you need from there.

**Comment by mikkopaderes** [comment]
Closing issue as question has been answered
