### ISSUE TITLE
dummy application showing relationships 

### ISSUE THREAD

**Issue by gvelesandro** [mikkopaderes/ember-cloud-firestore-adapter#82]
Please publish a dummy application or provide working examples of configuring data models for various relationships, including examples of CRUD methods.

For example, I'm having a hard time configuring two models with many-to-many relationships, where references are stored in their respective sub-collections.

**Comment by mikkopaderes** [comment]
I'll update the guides.

There's a gotcha regarding saving many-to-many. Basically you need to manually save them using the include hook in the `adapterOptions`. This is because we can't tell if a relationship has been removed or was just not loaded yet because someone used the `limit` query on it.

The alternative was to completely overwrite the relationships by deleting them all and writing once again. This wouldn't be ideal.

**Comment by gvelesandro** [comment]
Thanks. It would be nice to see a barebones dummy app with working CRUD examples of each relationship type (zero-to-many and many-to-many).  For zero-to-many, it would be nice to see examples of both storage models (referenced and fully-nested sub-collections).


________________________________

**Comment by mikkopaderes** [comment]
I've updated the guides. Relevant stuff for you should be [here](https://github.com/mikkopaderes/ember-cloud-firestore-adapter/blob/master/guides/04-creating-updating-deleting-records.md#saving-relationships).

I'll try to find some time to make the dummy app comprehensive. In the meantime, I think this guide update should suffice for your case.

**Comment by gvelesandro** [comment]
Thank you.  In these updated examples, can you include snippets of data model definitions for relevant types, such as user, reminder, and group?


________________________________

**Comment by mikkopaderes** [comment]
There's nothing special about it really. Just plain old Ember Data `hasMany` and `belongsTo` syntax.

I try not to repeat regular Ember Data stuff in the guides to avoid bloating it but if it helps, I'll add it some time today.

**Comment by gvelesandro** [comment]
Thanks, will give it a try!


________________________________

**Comment by gvelesandro** [comment]
I've given the many-to-many example a try, and here are my issues:

Assuming that the `user` object could have multiple `groups` during **create** action: `groups: [someGroup1, someGroup2,...]`. So, I'm assuming that there has to be a `forEach` loop inside of the create.save `include` function to bind each group to user. 

While this works well for **create**, how will this work for **edit**, where some groups could be added and others removed, and each has to be compared?  In other words, is there an efficient way to compare old and new groups each **edit**, and update the data accordingly?

A side note:  `batch.set(db.collection('users').doc(newUser.get('id')).collection('groups'))` throws an exception. `Batch.set` requires a document reference, not a collection reference. This appears to be an issue across all adapter documentation for this repo. This solves it:  `batch.set(db.collection('users').doc(newUser.get('id')).collection('groups').doc(group.get('id'))`

**Comment by mikkopaderes** [comment]
Yes my bad about those batch examples. It's basically the same write batch in Firestore JS SDK so whatever works there will work here.

For the deletions, no there is no easy way. Ember Data currently doesn't provide any API for it. You'll have to track it yourself and do `batch.delete`.

**Comment by gvelesandro** [comment]
Your examples were enough to get me _unstuck_. Thank you!
