### ISSUE TITLE
model name in find doesn't match normal ED syntax

### ISSUE THREAD

**Issue by brendanoh** [mikkopaderes/ember-cloud-firestore-adapter#89]
When fetching a model called blog-post in emberfire I used to call

`this.store.findAll('blog-post');`

But with this adapter i have to use:

`this.store.findAll('blogPost');`

Is this intentional?

Brendan

**Comment by mikkopaderes** [comment]
Not intentional. I assumed that Ember Data handles that for you. I'll look into it.

**Comment by mikkopaderes** [comment]
I've just tried using `blog-post` and it worked in the sense that it would look under the `blogPosts` collection. It seems that Ember Data does handle it for you.

**Comment by brendanoh** [comment]
You are right I wasnt getting results cause of the realtime issue in #90
