### ISSUE TITLE
isRealtime issues

### ISSUE THREAD

**Issue by brendanoh** [mikkopaderes/ember-cloud-firestore-adapter#90]
Currently this doesnt return any values in my app:

`{ adapterOptions: { isRealtime: false } }`

However this gives me records but also socketio errors:

`{ adapterOptions: { isRealtime: true } }`

Anyone else had this issue?

**Comment by mikkopaderes** [comment]
What is the socketio errors? Also you don't need to set `isRealtime` if its value would be false. Although that should still work, may I see some code snippets on how you're calling things?

**Comment by brendanoh** [comment]
This issue was related to a conflict with another package so closing.
