### ISSUE TITLE
Support FastBoot authentication

### ISSUE THREAD

**Issue by mikkopaderes** [mikkopaderes/ember-cloud-firestore-adapter#99]
Firebase auth uses JWT tokens for authentication, not cookies. JWT tokens are short live so if we pass that in to the server through cookies and verify it, there's a high chance that it's already expired.

[Service workers](https://firebase.google.com/docs/auth/web/service-worker-sessions) might work although I haven't tried this solution yet.

Here's the flow of I think FastBoot auth could work:

1. Have a service worker that intercepts `fetch` and modify to add the result of [`getIdToken()`](https://firebase.google.com/docs/reference/js/firebase.User#get-idtoken)
2. In FastBoot server, verify the token through [`verifyIdToken()`](https://firebase.google.com/docs/reference/admin/node/admin.auth.Auth.html#verifyidtoken).
3. Once the verification succeeds, we generate a custom token through [`createCustomToken()`](https://firebase.google.com/docs/reference/admin/node/admin.auth.Auth.html#create-custom-token).
4. We then pass-in the custom token in the request header to Ember FastBoot (maybe in Authorization header?)
5. In Ember FastBoot, we [access the token through the header](http://ember-fastboot.com/docs/user-guide#access-request-headers) and use it in the ESA authenticator [`restore()`](https://github.com/mikkopaderes/ember-cloud-firestore-adapter/blob/master/addon/authenticators/firebase.js#L45) hook. We'll be using [`signInWithCustomToken()`](https://firebase.google.com/docs/reference/js/firebase.auth.Auth#sign-inwith-custom-token) to finally sign in the user.

This addon can support points 1 and 5 although I'm still contemplating if we should have 1 built-in. Points 2, 3, and 4 would have to be done in the FastBoot server which is out of our control.

**Comment by chadRoberge** [comment]
https://github.com/dockyard/ember-service-worker Is an add on I use with my projects and works well.  Might be easier to implement that.
